# Generated by Django 5.2.2 on 2025-06-15 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0002_rename_message_content_message_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_to', to='messagerie.message'),
        ),
    ]
