# Generated by Django 5.2.2 on 2025-06-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=155, null=True, unique=True),
        ),
    ]
