# Generated by Django 5.2.2 on 2025-06-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_adresse_user_latitude_user_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marque_voiture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='adresse',
            field=models.CharField(blank=True, default='Abomey-Calavi', max_length=255, null=True, verbose_name='Adresse'),
        ),
    ]
