# Generated by Django 5.2.2 on 2025-06-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_latitude_alter_user_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name=' Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='numero_telephone',
            field=models.CharField(max_length=15, verbose_name='Numéro de téléphone'),
        ),
    ]
