<<<<<<<< HEAD:gotogether/authentication/migrations/0008_user_marque_voiture_alter_user_adresse_and_more.py
# Generated by Django 5.2.2 on 2025-06-17 07:59
========
# Generated by Django 5.2.2 on 2025-06-17 13:30
>>>>>>>> d5e9e00 (style de la page de profil):gotogether/authentication/migrations/0006_user_first_login_user_marque_voiture_and_more.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='marque_voiture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name=' Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='user',
            name='numero_telephone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Numéro de téléphone'),
        ),
    ]
