# Generated by Django 5.2.2 on 2025-06-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_marque_voiture_alter_user_adresse'),
        ('authentication', '0005_alter_user_email_alter_user_numero_telephone'),
    ]

    operations = [
    ]
