# Generated by Django 5.2.1 on 2025-06-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_email_alter_user_numero_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adresse_arrivee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse_arrivee'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_depart',
            field=models.DateField(blank=True, null=True, verbose_name='Date de depart'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude_arrivee',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True, verbose_name='Latitude_arrivee'),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude_arrivee',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True, verbose_name='Longitude_arrivee'),
        ),
        migrations.AddField(
            model_name='user',
            name='marque_voiture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name=' Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='user',
            name='numero_telephone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Numéro de téléphone'),
        ),
    ]
