# Generated by Django 5.2.2 on 2025-06-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('authentication', '0005_alter_user_email_alter_user_numero_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
