# Generated by Django 5.2.1 on 2025-06-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adresse_arrivee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse_arrivee'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_depart',
            field=models.DateField(blank=True, null=True, verbose_name='Date de depart'),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude_arrivee',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True, verbose_name='Latitude_arrivee'),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude_arrivee',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True, verbose_name='Longitude_arrivee'),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True, verbose_name='Longitude'),
        ),
    ]
