# Generated by Django 5.2.1 on 2025-06-16 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infos_recomandations', models.CharField(blank=True, default='RAS', max_length=155, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conducteur_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infos_recomandations', models.CharField(blank=True, default='RAS', max_length=155, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrajetOffert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_depart', models.CharField(max_length=255)),
                ('latitude_depart', models.FloatField()),
                ('longitude_depart', models.FloatField()),
                ('heure_depart_prevue', models.DateTimeField()),
                ('adresse_arrivee', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude_arrivee', models.FloatField(blank=True, null=True)),
                ('longitude_arrivee', models.FloatField(blank=True, null=True)),
                ('heure_arrivee_prevue', models.DateTimeField(blank=True, null=True)),
                ('nb_places_disponibles', models.IntegerField(default=1)),
                ('est_actif', models.BooleanField(default=True)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets_offerts', to='algorithme.conducteur')),
            ],
            options={
                'ordering': ['heure_depart_prevue'],
            },
        ),
    ]
