# Generated by Django 5.2.1 on 2025-06-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude_client', models.FloatField()),
                ('longitude_client', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude_conducteur', models.FloatField()),
                ('longitude_conducteur', models.FloatField()),
                ('nb_places', models.IntegerField(max_length=5)),
            ],
        ),
    ]
