# Generated by Django 5.2.1 on 2025-06-17 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeTrajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_depart', models.CharField(max_length=255)),
                ('latitude_depart', models.FloatField()),
                ('longitude_depart', models.FloatField()),
                ('heure_depart_prevue', models.DateTimeField()),
                ('adresse_arrivee', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude_arrivee', models.FloatField(blank=True, null=True)),
                ('longitude_arrivee', models.FloatField(blank=True, null=True)),
                ('heure_arrivee_prevue', models.DateTimeField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('passager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_trajet', to='algorithme.passager')),
            ],
            options={
                'ordering': ['heure_depart_prevue'],
            },
        ),
    ]
