# Generated by Django 5.2.1 on 2025-06-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.CharField(default='Abomey-Calavi', max_length=255),
        ),
        migrations.AddField(
            model_name='conducteur',
            name='adresse',
            field=models.CharField(default='Abomey-Calavi', max_length=255),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='nb_places',
            field=models.IntegerField(),
        ),
    ]
