# Generated by Django 5.2.2 on 2025-06-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithme', '0002_client_adresse_conducteur_adresse_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Conducteur',
        ),
    ]
