# Generated by Django 5.2.2 on 2025-06-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithme', '0002_client_adresse_conducteur_adresse_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='passager',
        ),
        migrations.RenameField(
            model_name='passager',
            old_name='latitude_client',
            new_name='latitude_passager',
        ),
        migrations.RenameField(
            model_name='passager',
            old_name='longitude_client',
            new_name='longitude_passager',
        ),
    ]
