# Generated by Django 5.2.1 on 2025-06-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passager',
            name='date_depart_passager',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='passager',
            name='heure_arrivee_passager',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passager',
            name='heure_depart_passager',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
