# Generated by Django 5.2.2 on 2025-06-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithme', '0003_delete_client_delete_conducteur'),
        ('algorithme', '0003_rename_client_passager_and_more'),
    ]

    operations = [
    ]
