# Generated by Django 5.2.1 on 2025-06-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithme', '0003_passager_date_depart_passager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajetoffert',
            name='date_depart',
            field=models.DateField(null=True),
        ),
    ]
