# Generated by Django 5.2.1 on 2025-06-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithme', '0004_trajetoffert_date_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducteur',
            name='infos_recomandations',
            field=models.CharField(blank=True, default='RAS', max_length=155, null=True),
        ),
    ]
