# Generated by Django 5.2.1 on 2025-06-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithme', '0006_alter_passager_infos_recomandations'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandetrajet',
            name='date_depart',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='demandetrajet',
            name='heure_arrivee_prevue',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandetrajet',
            name='heure_depart_prevue',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='trajetoffert',
            name='heure_depart_prevue',
            field=models.TimeField(),
        ),
    ]
