# Generated by Django 5.2.1 on 2025-06-18 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithme', '0007_demandetrajet_date_depart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajetoffert',
            name='date_depart',
            field=models.DateField(default=datetime.datetime(2025, 6, 18, 17, 4, 40, 419512, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trajetoffert',
            name='heure_arrivee_prevue',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
